# -*- coding: utf-8 -*-
"""seq_math_cluster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Hg_qDisImDUrSzO6rZfhE4mK0ezDulW
"""

import numpy as np

import pandas as pd

pip install textdistance

import textdistance as td

castDf = pd.read_stata('cast.dta')
castDf.head()

castDf['id12anm_ihds2_upd'] = castDf['id12anm_ihds2'].copy()
castDf

castDf

castDf['id12anm_ihds2_upd'][4590]

ptr = 0
castList = []
castList.append(castDf['id12anm_ihds2_upd'][0])
for i in range(1,len(castDf)):
    count = 0
    for j in range(len(castList)):
        if(td.sorensen.normalized_similarity(castDf['id12anm_ihds2_upd'][i].lower(),castList[j].lower())>0.75):
            castDf['id12anm_ihds2_upd'][i] = castList[j]
            count += 1
    if(count == 0):
        castList.append(castDf['id12anm_ihds2_upd'][i])

a = "Vannier"
b = "vannyer"

print(td.sorensen.normalized_similarity(a.lower(),b.lower()))

listCastUnique = []
for i in range(5,400):
    if(castDf['id12anm_ihds2'][i] != ""):
        listCastUnique.append(castDf['id12anm_ihds2'][i])
listCastUnique[:10]

listCastUnique2 = listCastUnique.copy()

len(set(listCastUnique2))

len(listCastUnique)

castList = []
castList.append(listCastUnique[0])
for i in range(1,len(listCastUnique)):
    count = 0
    for j in range(len(castList)):
        if(td.sorensen.normalized_similarity(listCastUnique[i].lower(),castList[j].lower())>0.65):
            listCastUnique[i] = castList[j]
            count += 1
    if(count == 0):
        castList.append(listCastUnique[i])

castList

len(castList)

listCastUnique.sort()
listCastUnique

